#!/usr/bin/env ruby

require 'sinatra'
require 'haml'

require 'shoplex'

set :root,          File.dirname(__FILE__)
set :public_folder, Proc.new { File.join(root, "..", "webui") }
set :static,        true

get '/' do
  content_type "text/html"
  @open_file_upload_dialog = true
  haml :index
end

post '/' do
  unless params[:file] &&
         (tmpfile = params[:file][:tempfile]) &&
         (name = params[:file][:filename])
    @open_file_upload_dialog = true
    @error = "No file selected"
    return haml(:index)
  end
  @open_file_upload_dialog = false
  tmpfile_content = tmpfile.read
  @result = Shoplex::process tmpfile_content
  haml :index
end

# Sinatra & Ruby Magic
__END__

@@layout
!!! 5
%html{:"data-theme" => "dark"}
  %head
    %meta{:charset => "utf-8"}
    %title Shoplex WEB
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}
    :css
      :root {
        --primary: #8e24aa;
      }
    %link{:rel => "stylesheet", :href => "/assets/pico.min.css"}
    :css
      /* Purple Dark scheme (Forced) */
      [data-theme="dark"] {
        --primary: #8e24aa;
        --primary-hover: #9c27b0;
        --primary-focus: rgba(142, 36, 170, 0.25);
        --primary-inverse: #FFF;
      }
      /* Purple (Common styles) */
      :root {
        --form-element-active-border-color: var(--primary);
        --form-element-focus-color: var(--primary-focus);
        --switch-color: var(--primary-inverse);
        --switch-checked-background-color: var(--primary);
      }
      h1 {
        --typography-spacing-vertical: 1rem;
      }
  %body
    %main.container
      != yield

@@index
%h1 Shoplex
%em(style="color: red")=@error
%details(open=@open_file_upload_dialog)
  %summary File Upload
  %form{action: "/", method: "post", enctype: "multipart/form-data"}
    .grid
      %div
        %input{type: "file", name: "file"}
      %div
        %input{type: "submit", value: "Upload"}
%details
  %summary Text Upload
  %form{action: "/", method: "post", enctype: "multipart/form-data"}
    %textarea{name: 'textarea', placeholder: "copy your text here"}
    %input{type: "submit", value: "Upload"}
%hr
- if @result
  %h2 Result
  %h3 Errors and invoices to look out for
  %div(style="color: red")
    Errors here
  %h3 Lexware file
  %a{role: 'button', href:"data:attachment/csv;charset=utf-8,#{URI.encode_www_form_component @result}", target: '_blank', download: 'filename.csv'}
    Download file
  %pre
    = @result
